server {
  listen 80;
  server_name _;
  absolute_redirect off;

  root /usr/share/nginx/html;
  index index.html;

  location = / {
    return 302 /canvas/;
  }

  location = /canvas {
    return 301 /canvas/;
  }

  location /canvas/ {
    try_files $uri $uri/ /canvas/index.html;
  }
}
